name: Build and Publish

on:
  # run it on push to the repository
  push:
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: self-hosted

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - run: echo "TAG=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_ENV
      # - run: echo "BRANCH=$(git branch -a --contains ${{ env.TAG }} | grep -v HEAD | cut -d '/' -f3)" | tee -a $GITHUB_ENV

      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          platforms: linux/amd64,linux/arm64
          # Note: tags has to be all lower-case
          tags: |
            jakoberpf/zerotier-bridge:latest 
          # build on feature branches, push only on master branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          platforms: linux/amd64,linux/arm64
          # Note: tags has to be all lower-case
          tags: jakoberpf/zerotier-bridge:${{ env.BRANCH }} # ${{ env.TAG }}${{ env.BRANCH }}
          # build on feature branches, push only on master branch
          push: ${{ github.ref != 'refs/heads/master' }}
          build-args: |
              BRANCH=${{ env.BRANCH }} 
          # | sed -r 's,/,-,g'

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}